services:
  backend:
    build: ./backend
    ports:
      - "8080:80"

  frontend: 
    depends_on:
      - backend
    build: ./frontend
    ports:
      - "8081:8080"
    environment:
      - VITE_API_BASE_URL=http://127.0.0.1:8080/query_health_condition/
  